#!/bin/bash

echo "Installing Java..."

sudo yum update -y
sudo yum install java-17-amazon-corretto -y

echo "Downloading Apache Tomcat..."

wget https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.44/bin/apache-tomcat-10.1.44.tar.gz

echo "Extracting Apache Tomcat..."

tar -xvf apache-tomcat-10.1.44.tar.gz

echo "Apache Tomcat installed successfully."
